trigger: 
- master

schedules:
  - cron: "00 08 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "15 08 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "00 10 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "00 11 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "00 15 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "00 16 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true
  - cron: "00 17 * * Mon,Tue,Wed,Thu,Fri"
    displayName: Execucao diaria
    branches:
      include:
        - master
    always: true


#pool:
#   vmImage: 'ubuntu-latest'
pool:
  name: Pool-Tester
  demands: java

steps:

#- task: Maven@3
- task: Bash@3
  displayName: Build with Maven
  inputs:
      targetType: 'inline'
  #    script: mvn -f Fonte/pom.xml -Dtest.ambiente=dev test package
      script: mvn -f Fonte/pom.xml -Djavax.net.ssl.trustStore=/azp/_work/1/s/cacerts -Dtest.ambiente=dev test package
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true


